language: csharp
os: linux
dist: trusty
sudo: required
dotnet: 2.1.300
mono: none
env: DOTNETCORE=1

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/dotnet-build.sh
  - chmod +x ./scripts/dotnet-publish.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi